# Generated by Django 5.0.7 on 2024-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employeemodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(default='', upload_to='emp_profile_img'),
        ),
    ]
