# Generated by Django 5.0.7 on 2024-09-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
