# Generated by Django 5.0.7 on 2024-09-17 10:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_rename_type_media_media_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='media',
            managers=[
                ('audio', django.db.models.manager.Manager()),
            ],
        ),
    ]
